---
language: ruby
bundler_args: --without development
script: "bundle exec rake test SPEC_OPTS='--format documentation'"
rvm:
  - 1.9.3
  - 2.0.0
env:
  matrix:
    - MCOLLECTIVE_GEM_VERSION="~> 2.2.0"
    - MCOLLECTIVE_GEM_VERSION="~> 2.4.0"
    - MCOLLECTIVE_GEM_VERSION="~> 2.5.0"
    - MCOLLECTIVE_GEM_VERSION="~> 2.6.0"
    - MCOLLECTIVE_GEM_VERSION="~> 2.7.0"
notifications:
  email: false
